In [10]:
import numpy as np 
import pandas as pd

In [11]:
df = pd.read_csv("../01_Dataset/01_raw/Heart_raw_uncleaned.csv")
df.head()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No

**COMFIRMING THE MISSING VALUES**

In [12]:
df.isnull().sum()

HeartDisease         0
BMI                 91
Smoking             67
AlcoholDrinking      0
Stroke               0
PhysicalHealth      67
MentalHealth         0
DiffWalking          0
Sex                  0
AgeCategory          0
Race                 0
Diabetic             0
PhysicalActivity     0
GenHealth           46
SleepTime           45
Asthma               0
KidneyDisease        0
SkinCancer           0
dtype: int64

In [13]:
df["BMI"] = df["BMI"].fillna(df["BMI"].median())

In [14]:
df["Smoking"] = df["Smoking"].fillna(df["Smoking"].mode()[0])

In [15]:
df["PhysicalHealth"] = df["PhysicalHealth"].fillna(df["PhysicalHealth"].mode()[0])

In [16]:
df["GenHealth"] = df["GenHealth"].fillna(df["GenHealth"].mode()[0])

In [17]:
df["SleepTime"] = df["SleepTime"].fillna(df["SleepTime"].median())

In [18]:
df.isnull().sum()

HeartDisease        0
BMI                 0
Smoking             0
AlcoholDrinking     0
Stroke              0
PhysicalHealth      0
MentalHealth        0
DiffWalking         0
Sex                 0
AgeCategory         0
Race                0
Diabetic            0
PhysicalActivity    0
GenHealth           0
SleepTime           0
Asthma              0
KidneyDisease       0
SkinCancer          0
dtype: int64

**REMOVING THE DUPLICATE VALUES**

In [20]:
df = df.drop_duplicates()

In [22]:
df.shape
df

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,No,16.60,Yes,No,No,3.0,30,No,Female,55-59,White,Yes,Yes,Very good,5.0,Yes,No,Yes
1,No,20.34,No,No,Yes,0.0,0,No,Female,80 or older,White,No,Yes,Very good,7.0,No,No,No
2,No,26.58,Yes,No,No,20.0,30,No,Male,65-69,White,Yes,Yes,Fair,8.0,Yes,No,No
3,No,24.21,No,No,No,0.0,0,No,Female,75-79,White,No,No,Good,6.0,No,No,Yes
4,No,23.71,No,No,No,28.0,0,Yes,Female,40-44,White,No,Yes,Very good,8.0,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4495,No,23.17,Yes,No,No,0.0,0,No,Female,75-79,White,No,No,Good,8.0,No,No,No
4496,No,27.46,Yes,No,No,0.0,0,No,Female,40-44,Asian,No,Yes,Good,7.0,No,No,No
4497,No,25.79,Yes,No,No,0.0,0,No,Female,50-54,White,No,Yes,Excellent,6.0,No,No,No
4498,No,23.30,Yes,No,No,0.0,0,No,Female,50-54,White,No,Yes,Very good,8.0,No,No,No
4499,No,43.24,Yes,No,No,30.0,30,Yes,Male,65-69,Other,No,Yes,Good,4.0,No,No,No

In [ ]:
df.select_dtypes(include=["int64","float64"]).columns

Index(['BMI', 'PhysicalHealth', 'MentalHealth', 'SleepTime'], dtype='str')

**FOR NUMERICAL INVALID VALUE**

In [25]:
df[["BMI", "PhysicalHealth", "SleepTime", "MentalHealth"]].describe()

               BMI  PhysicalHealth    SleepTime  MentalHealth
count  4493.000000      4493.00000  4493.000000   4493.000000
mean     29.303056         4.05030     7.041398      4.446472
std       6.708174         8.52147     1.590145      8.598370
min       2.900000         0.00000     1.000000      0.000000
25%      24.800000         0.00000     6.000000      0.000000
50%      28.250000         0.00000     7.000000      0.000000
75%      32.890000         3.00000     8.000000      5.000000
max      80.000000        30.00000    20.000000     30.000000

In [30]:
for columns in df.select_dtypes(include=["object"]).columns:
    print(f"\n{columns}:")
    print(df[columns].unique())

HeartDisease:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Smoking:
<StringArray>
['Yes', 'No', 'YES', 'No ', 'yes']
Length: 5, dtype: str

AlcoholDrinking:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Stroke:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

DiffWalking:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

Sex:
<StringArray>
['Female', 'Male']
Length: 2, dtype: str

AgeCategory:
<StringArray>
[      '55-59', '80 or older',       '65-69',       '75-79',       '40-44',
       '70-74',       '60-64',       '50-54',       '45-49',       '18-24',
       '35-39',       '30-34',       '25-29']
Length: 13, dtype: str

Race:
<StringArray>
[                         'White',                          'Black',
                          'Asian', 'American Indian/Alaskan Native',
                          'Other',                       'Hispanic']
Length: 6, dtype: str

Diabetic:
<StringArray>
['Yes', 'No', 'No, borderline diabetes', 'Yes (during pregnancy)']
Length: 4, dtype: str

PhysicalActivity:
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

GenHealth:
<StringArray>
['Very good', 'Fair', 'Good', 'Poor', 'Excellent']
Length: 5, dtype: str

Asthma:
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

KidneyDisease:
<StringArray>
['No', 'Yes']
Length: 2, dtype: str

SkinCancer:
<StringArray>
['Yes', 'No']
Length: 2, dtype: str

C:\Users\chira\AppData\Local\Temp\ipykernel_8136\1646618621.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for columns in df.select_dtypes(include=["object"]).columns:

**SAVING THE FILE IN CLEANED FOLDER**

In [31]:
df = df.to_csv("../01_Dataset/02_cleaned/Heart_cleaned.csv", index=False)